<div class="banner-principal">
    <div id="owl-banner-principal" class="owl-carousel"> 
        <div class="item">
            <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-principal.png" alt="" />
        </div>
        <div class="item">
            <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-principal.png" alt="" />
        </div>
        <div class="item">
            <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-principal.png" alt="" />
        </div>
    </div>
</div>
<div class="banner-secundario">
    <ul>
        <li class="banner-secundario01">
            <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-secundario-01.png" alt="" />
        </li>
        <li class="banner-secundario02">
            <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-secundario-01.png" alt="" />
        </li>
        <li class="banner-secundario03">
            <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-secundario-01.png" alt="" />
        </li>
    </ul>
</div>