<div class="banner-principal" style="    max-width: 1280px;   width: 100%; overgabrielqs: hidden; ">
    <div id="owl-banner-principal" class="owl-carousel">
        <div class="item">
            <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-principal2.png" alt="" />
        </div>
        <div class="item">
            <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-principal2.png" alt="" />
        </div>
        <div class="item">
            <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-principal2.png" alt="" />
        </div>
    </div>
</div>
 