<div class="col2-set center banners-home-gabrielqs">
    <div class="col-1">
        <div class="banner-principal">
            <div id="owl-banner-principal" class="owl-carousel"> 
                <div class="item">
                    <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-principal3.png" alt="" />
                </div>
                <div class="item">
                    <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-principal3.png" alt="" />
                </div>
                <div class="item">
                    <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-principal3.png" alt="" />
                </div>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="banner-secundario">
            <ul>
                <li class="banner-secundario01">
                    <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-secundario-02.png" alt="" />
                </li>
                <li class="banner-secundario02">
                    <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-secundario-02.png" alt="" />
                </li>
                <li class="banner-secundario03">
                    <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-secundario-02.png" alt="" />
                </li>
                <li class="banner-secundario04">
                    <img src="/static/frontend/Gabrielqs/gabrielqsbase/web/images/banner-secundario-02.png" alt="" />
                </li>
            </ul>
        </div>
    </div>
</div>